name : Deploy to production
on:
    push:
        branches:
            - "main"

jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to production cluster


        steps:
            - name: Checkout
              uses: actions/checkout@v4 # Checkout the code from the repository

            - name: Setup SSH key
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key

            - name: Deploy to production
              run: |
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.207.247.177 << 'EOF'
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                export PATH="$NVM_DIR/versions/node/v22.13.1/bin:$PATH"
                cd cicdbms/ && git pull
                pnpm install
                pnpm run build
                pm2 restart http-server
                pm2 restart ws-server
                pm2 restart web
                EOF
